### ISSUE TITLE
Queue Calculator?

### ISSUE THREAD

**Issue by DavidLangworthy** [gilliganondata/miscelleneous-explorations#1]
Would you mind putting up the source for your queue calculator?  I love it and want to add a few things.

Regardless, thanks a ton.  It has helped me a lot and saved me a ton of work.

**Comment by gilliganondata** [comment]
Can you be more specific? I'm not sure this is actually something I've done.

**Comment by DavidLangworthy** [comment]
Apologies, I must have gotten mixed up.  

Sorry for the bother.
